import os

import numpy as np
import pandas as pd

from db import get_engine

rng = np.random.default_rng(42)  # deterministic (move #3)
engine = get_engine()

cust = pd.read_sql("SELECT customer_id, channel FROM customers", engine)
prod = pd.read_sql(
    "SELECT product_id, product_name, default_unit_cost, default_unit_price FROM products",
    engine,
)
days = pd.read_sql("SELECT date FROM dates", engine)["date"]

N_ORDERS = 5000

# weighted customers: a couple dominate (Pareto-ish), not uniform
cust_weights = np.array([0.28, 0.22, 0.15, 0.12, 0.10, 0.08, 0.05])
cust_weights = cust_weights[: len(cust)] / cust_weights[: len(cust)].sum()
order_customer = rng.choice(cust.customer_id, size=N_ORDERS, p=cust_weights)

# weekend-light order dates
day_arr = np.array(days)
is_weekend = pd.to_datetime(days).dt.dayofweek.values >= 5
day_weights = np.where(is_weekend, 0.4, 1.0)
day_weights = day_weights / day_weights.sum()
order_dates = rng.choice(day_arr, size=N_ORDERS, p=day_weights)

orders = pd.DataFrame(
    {
        "order_id": np.arange(
            1, N_ORDERS + 1
        ),  # we'll need this to link lines; NOT the DB id
        "customer_id": order_customer,
        "order_date": order_dates,
    }
)

lines = []
for oid in orders.order_id:
    n = rng.integers(1, 5)  # 1..4 products
    picks = rng.choice(prod.index, size=n, replace=False)
    for pi in picks:
        p = prod.loc[pi]
        qty = int(rng.integers(5, 60))
        # price wobbles ±15% around the list price → realistic variation
        price = round(float(p.default_unit_price) * rng.uniform(0.85, 1.15), 2)
        lines.append(
            {
                "order_id": oid,
                "product": p.product_name,  # NAME, not id — the mess lives here
                "qty_cartons": qty,
                "unit_price": price,
                "unit_cost": float(p.default_unit_cost),
            }
        )
lines = pd.DataFrame(lines)

messy = lines.merge(orders, on="order_id").copy()


# defect 1: mixed date formats -----------------------------------------------
def messy_date(d):
    d = pd.Timestamp(d)
    style = rng.integers(0, 3)
    if style == 0:
        return d.strftime("%Y-%m-%d")  # 2024-03-15
    if style == 1:
        return d.strftime("%d/%m/%Y")  # 15/03/2024  (dayfirst!)
    return d.strftime("%B %d, %Y")  # March 15, 2024


messy["order_date"] = messy["order_date"].map(messy_date)


# defect 2: inconsistent product spelling/casing/whitespace ------------------
def messy_name(name):
    style = rng.integers(0, 4)
    if style == 0:
        return name  # clean
    if style == 1:
        return name.lower() + " "  # 'gala apple '
    if style == 2:
        return name.upper()  # 'GALA APPLE'
    return f"{name.split()[-1]} - {' '.join(name.split()[:-1])}"  # 'Apple - Gala'


messy["product"] = messy["product"].map(messy_name)


# defect 3: money as text with RM prefix + thousands commas -------------------
def messy_money(x):
    return f"RM {x:,.2f}" if rng.random() < 0.7 else str(x)  # mix of dirty & plain


messy["unit_price"] = messy["unit_price"].map(messy_money)

# defect 4: blank cells in qty / price ---------------------------------------
blank_idx = rng.choice(messy.index, size=int(len(messy) * 0.03), replace=False)
messy.loc[blank_idx, "qty_cartons"] = None

# column order a human would export (ugly, not your schema order) -------------
messy = messy[
    [
        "order_date",
        "customer_id",
        "product",
        "qty_cartons",
        "unit_price",
        "unit_cost",
        "order_id",
    ]
]

os.makedirs("data", exist_ok=True)
with pd.ExcelWriter("data/accounting_export.xlsx", engine="openpyxl") as w:
    messy.to_excel(w, sheet_name="Orders", startrow=2, index=False)
    # rows 0–1 left as junk, mimicking a merged-title ugly export
    ws = w.sheets["Orders"]
    ws["A1"] = "Chop Tong Guan Sdn Bhd — Sales Export"
    ws["A2"] = "Generated by AutoCount · CONFIDENTIAL"

print(f"wrote {len(messy)} messy order lines to data/accounting_export.xlsx")
